### ISSUE TITLE
should packs include "goodput" -- sanity tests that should pass?

### ISSUE THREAD

**Issue by pahp** [UMDLARS/dtanm#40] opened 2019-09-25 00:39 UTC
Originally, we had a daemon that added known good inputs so that people couldn't just spam attacks, or just call error() all the time... do we need to include some good inputs that should pass? How many?

**Comment by ChandlerSwift** [comment] 2019-09-25 17:48
This would be pretty easy to implement, practically: The pack could just include tarballs of attacks, and then those would be imported as created by the admin when the framework is started. 

Though that doesn't address the "how many" and "what inputs" questions.

**Comment by ChandlerSwift** [comment] 2020-07-21 02:29
I'm considering this a dupe of the more general #57, and possibly an issue that would need to be taken up at a pack level now that this is implemented.

**Closed by ChandlerSwift** 2020-07-21 02:29 UTC
